# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft
minecraft_version=26.2
minecraft_version_range=[26.2]

# NeoForge
neo_version=26.2.0.57
loader_version_range=[1,)

# Dependencies
fusion_version=1.3.4
fusion_minecraft_version=26.2
jei_version=30.2.0.15

# Mod properties
mod_id=laboratoryblocks
mod_name=Artemis' Laboratory Blocks
mod_license=MIT License
mod_version=0.8.4r
mod_group_id=de.artemis.laboratoryblocks
mod_authors=DoomedArtemis
mod_description=Upgrade your builds with modern, futuristic laboratory blocks inspired by the classic laboratory style.
