# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# NeoForge
neo_version=21.1.226
loader_version_range=[1,)

# Dependencies
fusion_minecraft_version=1.21.1
fusion_version=1.2.12
jei_version=19.22.0.315

# Mod properties
mod_id=laboratoryblocks
mod_name=Artemis' Laboratory Blocks
mod_license=MIT License
mod_version=0.8.4r
mod_group_id=de.artemis.laboratoryblocks
mod_authors=DoomedArtemis
mod_description=Upgrade your builds with modern, futuristic laboratory blocks inspired by the classic laboratory style.