# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20

# Minecraft
minecraft_version=1.21.12
minecraft_version_range=[1.21.11]

# NeoForge
neo_version=21.11.38-beta
loader_version_range=[1,)

# Dependencies
fusion_version=1.2.11
jei_version=27.4.0.17

# Mod properties
mod_id=laboratoryblocks
mod_name=Artemis' Laboratory Blocks
mod_license=MIT License
mod_version=0.8r
mod_group_id=de.artemis.laboratoryblocks
mod_authors=Artemis
mod_description=Upgrade your builds with modern, futuristic laboratory blocks inspired by the classic laboratory style.
