blank_issues_enabled: false

contact_links:
  - name: Community Support
    url: https://discord.intelligence-modding.de/
    about: Ask installation questions or get general help from the Intelligence Modding community.
